### ISSUE TITLE
Chosen - Selecting custom warning doesn't display text box or focus text box

### ISSUE THREAD

**Issue by Xon** [Xon/XenForo-WarningImprovements#20]
Had reports that when selecting the custom warning, the text box for the label isn't showing up consistantly.

**Comment by Xon** [comment]
Note; if the custom warning is shown, should focus the text entry field.

**Comment by jerpr** [comment]
I've tried to reproduce but haven't been able to so far, and I don't see anything suspect.

As for focusing the input, that might be difficult. Something in XF seems to focus the first non-disabled text input after making a selection. At first I thought it was the form filler, but it doesn't appear to be. Calling $input.focus() on the field after it is shown has no effect because the XF focus seems to be called afterwards. I'll keep digging though.

**Comment by Xon** [comment]
@jrahmy I thought reproducing it could be tricky but I had it happen to myself but a refresh made it go away and haven't been able to reproduce it since.

The focusing sounds annoying :(

**Comment by jerpr** [comment]
Still haven't been able to reproduce the original issue, but I figured out the focusing conflict. Disabler fields autofocus when they become enabled. Setting a brief timeout on focusing the custom warning title overcomes this.

I'll submit a PR for that shortly.

**Comment by jerpr** [comment]
Hmm, I may have spoken too soon. 

Focusing the title input on page load for the radio view doesn't work, even with a timeout (no matter the duration). The focus() method is called, but it simply removes focus from the Disabler field without focusing the title input. Strangely enough, the exact same function call seems to work fine when clicking the radio option *after* the initial page load.

Pushing what I have so far to a separate branch.

**Comment by Xon** [comment]
@jrahmy I just restored the code in the above PR, which got edited out by a silly XML export in https://github.com/Xon/XenForo-WarningImprovements/commit/30a6faf31274ee6c5691aa490503011eac7a7f09

It still looks broken :(

**Comment by Xon** [comment]
Horrible hack (https://github.com/Xon/XenForo-WarningImprovements/commit/a3b03336c141057c278246618de5bd7e816aaffd), but I don't care.
